### ISSUE TITLE
Get VSH ported to 1.7

### ISSUE THREAD

**Issue by WildCard65** [WildCard65/Versus-Saxton-Hale#17]
@FlaminSarge @Chdata Do you think it's now time to port VSH over to 1.7 newdecls since 1.7 is now out?

**Comment by Chdata** [comment]
If it means rewriting everything in new syntax no, if it's only change some things to a new syntax then sure. I personally don't feel like bothering until 1.7 is officially released just because if feels like it will be months before that happens.

**Comment by WildCard65** [comment]
Well, @Chdata if you look in SM news, 1.7 is RELEASED

**Comment by WildCard65** [comment]
1290d9d2a6c1e75a4d7cd9a45bbb441766d3413a marks beginning of 1.7 syntax port

**Comment by WildCard65** [comment]
Alright progress, https://github.com/WildCard65/Versus-Saxton-Hale/commit/abcd5cb921f4b83e4f3feaed1492dae435a3ce8f marks 50% done

**Comment by WildCard65** [comment]
The dual commit reference was because I forgot to add void to FindVersionData

**Comment by WildCard65** [comment]
https://github.com/WildCard65/Versus-Saxton-Hale/commit/6d653bf8c9f75b70e1deb9011f3a593e5b16226d Now marks complete(Just need to rebase branch onto develop then pr it)
