### ISSUE TITLE
Private chat shows to all players

### ISSUE THREAD

**Issue by yarik2720** [WildCard65/Versus-Saxton-Hale#23]
Private player chat displays to all players. Shows like damage dealt or next hale becoming.
![77ba24e6-d8bd-11e4-8b0c-5ec557827fd1](https://cloud.githubusercontent.com/assets/1839978/6996985/dd9451d8-dbb0-11e4-804a-a6852cecdfb9.jpg)

SourceMod Version: 1.7.1-dev+5171
[SM] Listing 36 plugins:
01 "[TF2] TF2Attributes" (1.1.1) by FlaminSarge
02 "Server Defense" (2.1) by Greyscale
03 "Admin Help" (1.7.1-dev+5171) by AlliedModders LLC
04 "Goomba Stomp TF2" (1.1.0) by Flyflo
05 "Basic Chat" (1.7.1-dev+5171) by AlliedModders LLC
06 "Mapchooser Extended Sounds" (1.10.2) by Powerlord
07 "Basic Info Triggers" (1.7.1-dev+5171) by AlliedModders LLC
08 "Sound Commands" (1.7.1-dev+5171) by AlliedModders LLC
09 "Nextmap" (1.7.1-dev+5171) by AlliedModders LLC
10 "TF2 Fast Respawns" (1.0.8) by WoZeR, MonkeyBiz, gH0sTy, Downtown1, Kevin_b_er, SaberUK, octo-dhd
11 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
12 "Observer Point" (1.0.100) by Dog
13 "TF2 Class Restrictions" (0.6) by Tsunami
14 "Basic Commands" (1.7.1-dev+5171) by AlliedModders LLC
15 "Fun Commands" (1.7.1-dev+5171) by AlliedModders LLC
16 "Advertisements" (0.6) by Tsunami
17 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
18 "Updater" (1.2.1) by GoD-Tony
19 "Versus Saxton Hale" (1.53) by Rainbolt Dash, FlaminSarge, Chdata, nergal, fiagram
20 "Admin File Reader" (1.7.1-dev+5171) by AlliedModders LLC
21 "NativeVotes" (0.8.3) by Powerlord
22 "[TF2Items] Manager" (1.4.1) by Damizean & Asherkin
23 "Client Preferences" (1.7.1-dev+5171) by AlliedModders LLC
24 "Advanced Infinite Ammo" (1.3.9) by Tylerst
25 "High Ping Kicker - Lite Edition" (1.0.0.1) by Liam
26 "SourceBans" (1.4.10) by SourceBans Development Team
27 "Player Commands" (1.7.1-dev+5171) by AlliedModders LLC
28 "Anti-Flood" (1.7.1-dev+5171) by AlliedModders LLC
29 "Fun Votes" (1.7.1-dev+5171) by AlliedModders LLC
30 "Goomba Stomp Core" (2.0.2) by Flyflo
31 "Basic Votes" (1.7.1-dev+5171) by AlliedModders LLC
32 "Basic Comm Control" (1.7.1-dev+5171) by AlliedModders LLC
33 "Admin Menu" (1.7.1-dev+5171) by AlliedModders LLC
34 "Reserved Slots" (1.7.1-dev+5171) by AlliedModders LLC
35 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
36 "Server Defense Menu" (1.5) by Greyscale

**Comment by WildCard65** [comment]
Is the green stuff the score earned?

**Comment by yarik2720** [comment]
@WildCard65 yes.

**Comment by WildCard65** [comment]
Does it happen at end of round or when ever someone dies?

**Comment by yarik2720** [comment]
@WildCard65 it happen instantly when some player have message from VSH plugin.

**Comment by WildCard65** [comment]
Well I looked through the code but I CPrintToChat in Timer_Damage but that shouldn't cause a CPrintToChatAll...

**Comment by yarik2720** [comment]
13 players on server and 13 text messages, only from hale plugin.
I also have advertisement plugin and it shows only one message
![ss 2015-04-05 at 05 55 30](https://cloud.githubusercontent.com/assets/1839978/6997233/16c6b52a-dbbd-11e4-998f-d1020954f3d2.jpg)

**Comment by WildCard65** [comment]
Mind trying https://github.com/WildCard65/Versus-Saxton-Hale/commit/d231ad14264c991d1085e9e450ce51c00f37b06d

**Comment by yarik2720** [comment]
issue fixed
