### ISSUE TITLE
Easter Bunny deals less damage than other Hales

### ISSUE THREAD

**Issue by Starblaster64** [WildCard65/Versus-Saxton-Hale#24]
His bottle deals +200% (195) instead of +210% (202), is this intended as a result of crit eggs after every kill? I haven't seen it mentioned anywhere.

**Comment by WildCard65** [comment]
@Chdata I think this calls for your answer.

**Comment by FlaminSarge** [comment]
It was probably a balance thing with the crit egg spawns to grant a bonus for chaining kills while at the same time preventing him from one-shotting some classes with his bottle to start the chain off.

**Comment by Chdata** [comment]
Yes it's still the egg spam. Afaik, it's intentional (didn't you make him Flame? lel)

I think it's best to keep that because he's also the only boss capable of killing overhealed heavies in one hit.

**Comment by Starblaster64** [comment]
Going to close this as I believe we have all the answers we need.
