### ISSUE TITLE
Natascha granting extra ammo

### ISSUE THREAD

**Issue by Starblaster64** [WildCard65/Versus-Saxton-Hale#26]
If a player equips the Natascha as heavy, they will still keep the extra 100 ammo that it grants when it is replaced with the stock minigun.

**Comment by WildCard65** [comment]
Does FF2 deal with that?

**Comment by Chdata** [comment]
Doesn't matter if FF2 does, it ought to be looked in to / fixed.

**Comment by Starblaster64** [comment]
Valve silently removed the extra ammo from the Natascha, possibly unintended, but if not then this issue is resolved for now.
