### ISSUE TITLE
Spy dispenser cloak drain rate potentially too high?

### ISSUE THREAD

**Issue by Starblaster64** [WildCard65/Versus-Saxton-Hale#28]
The rate at which a spy's cloak drains while activated next to a dispenser seems unreasonably high. If I want to heal up at a dispenser and Hale suddenly shows up, if I cloak to escape I'm going to lose a portion of my cloak meter without even getting out of Hale's reach.

EDIT: I suppose it depends on how close you were to the dispenser when you cloaked initially, so not as harsh as I make it out to be, still worth considering for other scenarios.

EDIT2: On second thought, it's probably fine how it is, there's only a few cases where having a lower drain rate would mean the difference between escaping and dying.

**Comment by Chdata** [comment]
It's supposed to drain fast to prevent hiding spies. It isn't too hard to decloak next to one to instead gain cloak back rapidly, especially if you lost sight of him. Plus it's not as if 99% of maps are covered in dispenser. Most dispensers also won't be out on in the midst of battle where you'll be trying to backstab.

**Comment by Starblaster64** [comment]
Yea, I realised that shortly after considering it. It escaped my mind that the drain is fast, but not *that* fast. Unless you can't move away from the dispenser for some absurd reason it's fine as it is.
