### ISSUE TITLE
Medigun Skins

### ISSUE THREAD

**Issue by Starblaster64** [WildCard65/Versus-Saxton-Hale#31]
With the addition of weapon skins in the latest major update, should the OVERRIDE_MEDIGUNS_ON define be enabled by default to allow people to show off their fancy (subjective) mediguns?

**Comment by WildCard65** [comment]
I have no idea. @FlaminSarge @Chdata how about you?

**Comment by Chdata** [comment]
probably yes

**Comment by WildCard65** [comment]
Alright then.

**Comment by WildCard65** [comment]
https://github.com/WildCard65/Versus-Saxton-Hale/commit/a7b48f06ff4458a0f3d8d10db4c615f979977be3 closes this
