### ISSUE TITLE
First round glitch occuring again

### ISSUE THREAD

**Issue by Starblaster64** [WildCard65/Versus-Saxton-Hale#35]
Probably due to Gun Mettle. Surviving the arena round and not changing class during the setup of the first Hale round will cause that player to not have any of their weapons have replaced attributes.

**Comment by WildCard65** [comment]
I'll try to figure it out sometime during the week

**Comment by Chdata** [comment]
Fixed in latest commit.

**Comment by WildCard65** [comment]
@Chdata Next time, add "Closes #<Issue number here>" into commit message to auto close it on push.
